# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitModelRcpp <- function(G, E, Y, standardize, grid, grid_size, grid_min_ratio, family, tolerance, max_iterations, min_working_set_size) {
    .Call('_hierNetGxE_fitModelRcpp', PACKAGE = 'hierNetGxE', G, E, Y, standardize, grid, grid_size, grid_min_ratio, family, tolerance, max_iterations, min_working_set_size)
}

