# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitModelCV <- function(G, E, Y, normalize, grid, family, tolerance, max_iterations, min_working_set_size, nfolds, seed, ncores, sparse_g) {
    .Call('_hierNetGxE_fitModelCV', PACKAGE = 'hierNetGxE', G, E, Y, normalize, grid, family, tolerance, max_iterations, min_working_set_size, nfolds, seed, ncores, sparse_g)
}

fitModel <- function(G, E, Y, weights, normalize, grid, family, tolerance, max_iterations, min_working_set_size, sparse_g) {
    .Call('_hierNetGxE_fitModel', PACKAGE = 'hierNetGxE', G, E, Y, weights, normalize, grid, family, tolerance, max_iterations, min_working_set_size, sparse_g)
}

